Update simulation_native.md
Added a fix for a possible error that occurred to me, also need to be fixed in the file gazebo_opticalflow_plugin. h 
#define HAS_GYRO TRUE to #define HAS_GYRO 1
otherwise this error crashes:
In file included from /home/fpvlive/catkin_ws/src/sitl_gazebo/src/gazebo_opticalflow_plugin.cpp:24:0:
/home/fpvlive/catkin_ws/src/sitl_gazebo/src/gazebo_opticalflow_plugin.cpp: In member function ‘virtual void gazebo::OpticalFlowPlugin::Load(gazebo::sensors::SensorPtr, sdf::ElementPtr)’:
/home/fpvlive/catkin_ws/src/sitl_gazebo/include/gazebo_opticalflow_plugin.h:43:18: error: ‘TRUE’ was not declared in this scope
 #define HAS_GYRO TRUE
                                   ^
/home/fpvlive/catkin_ws/src/sitl_gazebo/include/gazebo_opticalflow_plugin.h:43:18: note: in definition of macro ‘HAS_GYRO’
 #define HAS_GYRO TRUE
                                   ^~~~
sitl_gazebo/CMakeFiles/gazebo_opticalflow_plugin.dir/build.make:62: recipe for target 'sitl_gazebo/CMakeFiles/gazebo_opticalflow_plugin.dir/src/gazebo_opticalflow_plugin.cpp.o' failed
make[2]: *** [sitl_gazebo/CMakeFiles/gazebo_opticalflow_plugin.dir/src/gazebo_opticalflow_plugin.cpp.o] Error 1
CMakeFiles/Makefile2:2217: recipe for target 'sitl_gazebo/CMakeFiles/gazebo_opticalflow_plugin.dir/all' failed
make[1]: *** [sitl_gazebo/CMakeFiles/gazebo_opticalflow_plugin.dir/all] Error 2
Makefile:162: recipe for target 'all' failed

make: *** [all] Error 2